import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import * as T from './dist/vendor/three.module.js';
import {attachNavigation} from './dist/navigation.js';
registerHooks({resolve(s,c,next){if(s==='three')return {url:new URL('./dist/vendor/three.module.js',import.meta.url).href,shortCircuit:true};return next(s,c);}});
const {OrbitControls}=await import('./dist/vendor/OrbitControls.js');
const camera=new T.PerspectiveCamera(38,1,.1,100);camera.position.set(2,1,4);
const controls=new OrbitControls(camera,null);controls.update();
const nodes=new Map();const $=id=>{if(!nodes.has(id))nodes.set(id,{style:{},setAttribute(k,v){this[k]=v;}});return nodes.get(id);};
const nav=attachNavigation(camera,controls,$),relative=camera.position.clone().sub(controls.target),orientation=camera.quaternion.clone();
const right=new T.Vector3().setFromMatrixColumn(camera.matrixWorld,0),before=camera.position.clone();
$('#panRight').onclick();assert(camera.position.clone().sub(before).dot(right)<0);
for(const [x,y] of [[0,1],[-1,0],[0,-1]])nav.move(x,y);
assert(camera.position.clone().sub(controls.target).distanceTo(relative)<1e-10);
assert(camera.quaternion.angleTo(orientation)<1e-6);assert.equal(camera.zoom,1);
nav.mode('pan');assert.equal(controls.mouseButtons.LEFT,T.MOUSE.PAN);assert.equal(controls.touches.ONE,T.TOUCH.PAN);assert.equal($('#panMode')['aria-pressed'],'true');
nav.mode('rotate');assert.equal(controls.mouseButtons.RIGHT,T.MOUSE.PAN);assert.equal(controls.touches.TWO,T.TOUCH.DOLLY_PAN);
assert(controls.enablePan&&controls.screenSpacePanning);
console.log('Mouse/touch navigation modes and screen-relative movement preserve camera distance, orientation and zoom.');
