import {measurementsFor,renderMeasurements} from './dist/measurements.js';
import {acquisitionFor,renderAcquisition} from './dist/acquisition.js';
import {finishDiagram,diagramLabelsFor} from './dist/diagram-labels.js';
import {anatomyFor,renderAnatomy} from './dist/anatomy.js';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {phases,sources} from './dist/data.js';
import {drawExtra} from './dist/extra-diagrams.js';
import {renderUltrasound} from './dist/ultrasound.js';
const elements=new Map();const ctx=new Proxy({},{get:()=>()=>{}});
function el(s){if(!elements.has(s))elements.set(s,{innerHTML:'',textContent:'',hidden:false,value:0,checked:true,classList:{toggle(){}},setAttribute(k,v){this[k]=v;},focus(){},getContext:()=>ctx,showModal(){this.hidden=false;},close(){this.hidden=true;}});return elements.get(s);}
let registered;const storage=new Map();const sandbox={document:{querySelector:el,modelContext:{registerTool:t=>registered=t}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},phases,sources,drawExtra,renderUltrasound,renderMeasurements,renderAcquisition,renderAnatomy,finishDiagram,console,Set,Promise};
let code=await readFile('dist/app.js','utf8');code=code.replace("import {renderMeasurements} from './measurements.js?v=41';",'').replace("import {renderAcquisition} from './acquisition.js?v=41';",'').replace("import {finishDiagram} from './diagram-labels.js?v=41';",'').replace("import {renderAnatomy} from './anatomy.js?v=41';",'').replace("import {renderUltrasound} from './ultrasound.js?v=41';",'').replace("import {phases,sources} from './data.js?v=41';",'').replace("import {drawExtra} from './extra-diagrams.js?v=41';",'').replace(/setup3D\(\)\.catch\(\(\)=>\{.*?\}\);/s,'');vm.runInNewContext(code,sandbox);
assert.equal(registered.name,'select_fetal_view');let count=0;
for(let p=0;p<phases.length;p++){const seen=new Set();for(const lesson of phases[p].lessons){assert(!seen.has(lesson.id));seen.add(lesson.id);assert.equal(lesson.options.length,3);assert(lesson.checks.length>=3);assert(anatomyFor(lesson)?.items.length>=2);assert(diagramLabelsFor(lesson).length>=3);const r=registered.execute({trimester:p+1,viewId:lesson.id});assert.equal(r.title,lesson.title);assert.equal(el('#viewTitle').textContent,lesson.title);assert(el('#criteria').innerHTML.includes('이 뷰에서 관찰할 구조물'));assert(el('#criteria').innerHTML.includes('정확한 캘리퍼(측정자) 배치 기준'));assert(el('#criteria').innerHTML.includes(measurementsFor(lesson).rows[0].name));assert(el('#criteria').innerHTML.includes('영상 획득 시 주의해야 할 핵심 팁'));const protocol=acquisitionFor(lesson);assert(protocol);assert.equal(protocol.trimester,p+1);assert(protocol.steps.every(([label,text])=>label&&text&&el('#criteria').innerHTML.includes(text)));assert(el('#criteria').innerHTML.includes(`${p+1}분기 · Step-by-Step`));assert(el('#diagramLegend').innerHTML.includes(diagramLabelsFor(lesson)[0][0]));assert.equal(el('#schematicDetails').open,true);assert(el('#criteria').innerHTML.includes(anatomyFor(lesson).items[0]));el('#quiz').onclick({target:{closest:()=>({dataset:{answer:lesson.answer}})}});assert.match(el('#quiz .feedback').textContent,/정답/);el('#quiz').onclick({target:{closest:()=>({dataset:{answer:(lesson.answer+1)%3}})}});assert.match(el('#quiz .feedback').textContent,/다시/);el('#complete').onclick();assert.match(el('#complete').textContent,/완료됨/);el('#complete').onclick();assert.equal(el('#complete').textContent,'이 단면 학습 완료 ✓');count++;}}
const prior=el('#viewTitle').textContent;assert.throws(()=>registered.execute({trimester:0,viewId:'hc'}));assert.throws(()=>registered.execute({trimester:2,viewId:'missing'}));assert.equal(el('#viewTitle').textContent,prior);assert.equal(JSON.parse(storage.get('fetalview-progress')).length,0);console.log(`${count} lessons: selection, drawing branches, correct/incorrect answers, completion persistence and invalid tool input passed. Mock contract only; no browser/WebGL validation.`);

// Focused reading tabs retain their topic and reference choice across lesson/trimester changes.
el('#measurementTab').onclick();assert.equal(el('#measurementPanel').hidden,false);assert.equal(el('#acquisitionPanel').hidden,true);assert.equal(el('#measurementTab')['aria-selected'],'true');
el('#schematicTab').onclick();assert.equal(el('#ultrasoundReference').hidden,true);assert.equal(el('#schematicDetails').hidden,false);
el('#lessonSelect').onchange({target:{value:'2'}});assert.equal(el('#viewTitle').textContent,phases[2].lessons[2].title);assert.equal(el('#measurementPanel').hidden,false);assert.equal(el('#schematicDetails').hidden,false);
registered.execute({trimester:1,viewId:phases[0].lessons[0].id});assert.equal(el('#measurementPanel').hidden,false);assert.equal(el('#schematicDetails').hidden,false);
let prevented=false;el('#measurementTab').onkeydown({key:'ArrowRight',preventDefault(){prevented=true;}});assert(prevented);assert.equal(el('#qualityPanel').hidden,false);assert.equal(el('#criteriaTab').tabIndex,0);assert.equal(el('#measurementTab').tabIndex,-1);
el('#criteriaTab').onkeydown({key:'End',preventDefault(){}});assert.equal(el('#quiz').hidden,false);assert.equal(el('#criteria').hidden,true);
el('#quizTab').onkeydown({key:'Home',preventDefault(){}});assert.equal(el('#anatomyPanel').hidden,false);assert.equal(el('#quiz').hidden,true);
console.log('Reading/reference tabs, keyboard navigation and topic persistence across lessons/trimesters passed.');
